### ISSUE TITLE
How can I work with different param strings.

### ISSUE THREAD

**Issue by renilbabu03** [BlackBoxVision/typescript-hapi-starter#23]
This is one of the nicest repo. Thanks for creating such awesome project.

I am building api's where the url param id strings will be different.

e.g `/api/users/{USER_ID} , /api/products/{PRODUCT_ID}`.

But the current crud controller only supports {id}. 

How can I achieve this without overriding the crud controller. Is it doable.?

**Comment by JonatanSalas** [comment]
@renilbabu03 in the latest commit I have added the ability to pass a custom ID, check how to use it in the repo! And also let me know it the solution helps you 😄

**Comment by JonatanSalas** [comment]
@renilbabu03 closing issue!
