### ISSUE TITLE
NPM or Yarn?

### ISSUE THREAD

**Issue by laurilarjo** [BlackBoxVision/typescript-hapi-starter#27]
Hi @JonatanSalas, it's not a good idea to keep both, as it causes confusion. Also Heroku rejects the deployment if a project includes both `yarn.lock` and `package-lock.json`. This is why I originally removed the `package-lock.json`, but it seems you added it back recently. Maybe this was accidental? 
However, now when npm has developed so much, I'd like to remove yarn. Should I do that?

**Comment by JonatanSalas** [comment]
@laurilarjo yes, you can do that! It was accidental, sorry for that!
