### ISSUE TITLE
Add support for Auth with JWT or Sessions

### ISSUE THREAD

**Issue by JonatanSalas** [BlackBoxVision/typescript-hapi-starter#4]

**Comment by renilbabu03** [comment]
Any update on JWT authentication!

**Comment by JonatanSalas** [comment]
No! Currently we don't have a built-in solution. We're keeping the starter with the most minimal config

**Comment by renilbabu03** [comment]
@JonatanSalas . Right. That makes sense.

**Comment by laurilarjo** [comment]
Hi @JonatanSalas. It's been a long time since I looked at this project, but now I checked what's happened in here. I'd also like to keep things simple like you said earlier, so I'd like to close this issue.

**Comment by JonatanSalas** [comment]
@laurilarjo let's close it then!
